papersize: a4
number-sections: true
bibliography: references.bib  
fontsize: 12pt
linestretch: "1.5"
link-citations: true
csl: harvard-deutsch.csl
lang: de

format:
  pdf:
    documentclass: article
    margin-left: 20mm
    margin-right: 20mm
    margin-top: 25mm
    margin-bottom: 25mm
    include-before-body: tables.tex
    include-in-header: packages.tex
    keep-tex: true
    
    