# 09.11.2023 Presentation

## What is an Argument?

-   Claim: $A \uparrow \to B \uparrow$
-   Argument: because X (Reason)
    -   theoretical / empirical to support the claim
-   Purpose: convince audience of $\to$ claim

Example from AJR 2001

| A $\downarrow \implies$                            | B $\downarrow$         |
|----------------------------------------------------|------------------------|
| Quality of current institutions                    | Current Performance    |
| Empirical: Protection against Risk of Expropiation | reduces GDP per Capita |

Elements of X

-   Theory: countries with better property rights invest more in physical capital
-   Empirically: Figure 2 from Paper

Counterarguments:

-   reversed causality: $B \downarrow \to A \downarrow$
-   omitted vairable $A \downarrow \& B \downarrow$ because of W

Counter Counterarguments

-   accept limitations of argument
-   add reasons to X (X1,X2,...)

## Presentation

-   5 points per slide
-   short sentences

Questions:

-   policy advice
-   research addition
-   discussion about picture

Tips:

-   present the argument first
-   add colored lines to the figure for explanation (or text and formulas)
-   include regression formula (with arrows and explanation)
