---
title: "Our first session"
author: "My Name, my student ID"
output: html_notebook
---

# Session 1

Some text goes here.

```{r}
# Numeric 
x <- 5
x+2
y <-log(x)
z <- x^2 + y

# Characters

string_1 <- "a"
string_2 <- "my_last_name"


# Data Structures

# Vectors
v1 <- c(5,2,1,6,9,8)
v2 <- v1 +5
v3 <- v1 + v2
v4 <- c("Smith","Jackson","Ellison")
#v4 + 5

# Matrices
m_1 <- matrix(c(5,2,1,6,9,8), ncol = 2, nrow = 3)


# Lists
list_1 <- list(5,2,1,6,9,8)
list_2 <- list(c(5,2,1),c(6,9,8))
list_3 <- list("Jingle", "Bells", ",", "Jingle", "Bells",",", "Jingle", "all", "the", "way")
list_4 <- list(list_1,list_2, list_3)

```

More text goes here.

Live testing and answers to live questions are next.

```{r}
# Comments can be inserted via hashtag
# We can update objects by assigning a new value to them
x <-5 
x <- 9

# Objects are case-sensitive. This will not update "x" but create a new "X"
X <- 8

# We can comment out code we do not want run (instead of deleting it) 
# x <- NULL set x to NULL
# rm(x)   remove x from memory

# If we assign the output of some operation to an object, it will not be printed (result is not shown here or in the notebook)
myresult <- x/10

# If we we only perform the operation, the result is shown but the result is not saved to some object. 
x/10

# We can simply call an object to display it
myresult
```

```{r}
# Objects that are created in some previous code chunk can be used in later code chunks. The chunks are not isolated.
# We can perform the following computation with objects created above:
v2 + z
```

# Session 2

We continue with data structures, install/load/use our first library and access elements of data structures.

```{r warning=FALSE}
my_df <- data.frame("Last_Name" = c("Smith", "Jackson", "Ellison"),
                    "First_Name" = c("Joe", "Regina", "Donald"),
                    "Income" = c(2000,4000,1000)
                    )

library(data.table)

my_dt <- data.table("Last_Name" = c("Smith", "Jackson", "Ellison"),
                    "First_Name" = c("Joe", "Regina", "Donald"),
                    "Income" = c(2000,4000,1000)
                    )

# Accessing/retrieving/manipulating elements 

v1[4]+v1[6]
m_1[3,1]
list_1[4]
list_1[[4]]
list_2[[2]]
list_4[[3]]
list_4[[2]][[2]]
list_4[[1]][[4]]
list_4[[2]][[2]][[3]]

my_df$Income
my_df$Last_Name
my_df$Last_Name[2]

# my_df$Income[3] <- 1200
my_df$Income <- my_df$Income*12  
my_df$Income <- my_df$Income/12 
sum(my_df$Income)
mean(my_df$Income)

list_5 <- list_4
list_5[[4]] <- my_df

list_5[[4]]$First_Name[2]
list_5[[4]][["First_Name"]][[2]]
list_5[[4]][[2]][[2]]
```

## Factors

```{r}
factor_1 <- factor(x=c(1,3,5,5,5))
factor_1
```

Levels

```{r}
levels(factor_1) <- c("low", "medium", "high")
factor_1
```

## Functions

Example: Celsius to Fahrenheit

```{r}
celsius_to_fahrenheit <- function(celsius){
  fahren = 1.8*celsius+32
  return(fahren)
}
celsius_to_fahrenheit(10)
```

## Loops

```{r}
counter <- 0

print(counter)
for (x in 1:10) {
  print("yay")
  counter <- counter +1
}
print(counter)
```

```{r}
x <- c(2,34,56,7,43)
sum(x)

summe <- 0
for (y in x) {
  summe <- summe + y
}
summe
```
